Algoritmo "CALCULAR A MEDIA DO ALUNO "
// Disciplina  :  [Linguagem e Lógica de Programação]
// WERIDE MARCONDES DA SILVA NASCIMENTO
// Data atual  : 14/03/2020
Var
   N1,N2,N3,MEDIA:real
   NOME:CARACTERE
Inicio
   escreval("NOME")
   LEIA(NOME)
   escreval("N1")
   LEIA(N1)
   escreval("N2")                   '
   leia(N2)
   escreval("N3")                   '
   leia(N3)
   Escreval("")
   MEDIA:=(N1+N2+N3)/3)
   escrevaL("MEDIA DO ALUNO ", NOME," E =",MEDIA)
Fimalgoritmo