Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : PEDRO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2020
Var
N: INTEIRO


Inicio
ESCREVAL("DIGITE UM NUMERO")
LEIA(N)
SE N>10 ENTAO
ESCREVA("ESTE NUMERO É MAIOR QUE 10")
SENAO
ESCREVA("ESTE NUMERO É MENOR QUE 10")
FIMSE



Fimalgoritmo