Algoritmo "02 VALORES TROCADOS"
// Disciplina  :  [Linguagem e Lógica de Programação]
// WERIDE MARCONDES DA SILVA NASCIMENTO
// Data atual  : 14/03/2020
Var
   A,B:real
Inicio
   escreval("DIGITE O VALOR DE (A)")
   LEIA(A)
   ESCREVAL("")
   ESCREVAL ("DIGITE O VALOR DE (B)")
   LEIA (B)
   ESCREVAL("")
   ESCREVAL(" ENTÃO O VALOR DE A =",B)
   ESCREVAL(" ENTÃO O VALOR DE B =",A)
Fimalgoritmo