Algoritmo "03 ENTRE 100 E 200"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : PEDRO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/04/2020
Var
N: INTEIRO


Inicio
ESCREVAL("DIGITE UM NUMERO")
LEIA(N)
SE (N>= 100) e (N<=200) ENTAO
ESCREVA("este numero esta entre 100 e 200")
SENAO
ESCREVA("este numero nao esta entre 100 e 200")
FIMSE



Fimalgoritmo