Algoritmo " 03 multiplo de 3"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : PEDRO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/04/2020
Var
N :real



Inicio
escreval("digite um numero")
leia(N)

SE (N mod 3) = 0 entao
escreval("este numero é multiplo de 3")
SENÃO
escreval("este numero não é multiplo de 3")
fimse


Fimalgoritmo