Algoritmo "PRECO COM ACRECIMO%"
// Disciplina  :  [Linguagem e Lógica de Programação]
// WERIDE MARCONDES DA SILVA NASCIMENTO
// Data atual  : 14/03/2020
Var
   VM:real
   PCT:INTEIRO
Inicio
   escreval("ESCREVA O VALOR DA MERCADORIA: R$")
   LEIA(VM)
   ESCREVAL ("QUANTOS PORCENTO DE ACRECIMO: R$")
   LEIA (PCT)
   ESCREVAL("")
   escrevaL("SUA COMPRA JÁ COM ACRECIMO TOTALIZOL EM =",(VM*PCT)/100+VM)
Fimalgoritmo