Algoritmo " 07 CONSUMO MEDIO DE UM VEICULO "
// Disciplina  :  [Linguagem e Lógica de Programação]
// WERIDE MARCONDES DA SILVA NASCIMENTO
// Data atual  : 14/03/2020
Var
  DT,GC,consumo:real
Inicio
   escreval("DISTANCIA PERCORRIDA(Km)")
   LEIA(DT)
   escreval("")
   escreval("COMBUSTIVEL GASTO(l)")
   LEIA(GC)
   escreval("")
  consumo<-(DT/GC)
   escrevaL("O CONSUMO MEDIO GASTO NESTE PERCURSO FOI DE =",DT/GC," litros")
Fimalgoritmo