Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : PEDRO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/05/2020
Var
N: VETOR [1..3] DE INTEIRO
A: INTEIRO



Inicio
PARA A DE 1 ATE 3 FACA
ESCREVAL("DIGITE UM NUMERO",N[A])
LEIA(N[A])
FIMPARA
PARA N[A] DE 1 ATE 3 FACA
SE (N[A] MOD 2=0) ENTÃO
ESCREVA(N[A])
FIMSE
FIMPARA


Fimalgoritmo